





















.build_ano/uno/NilRTOS/nil.c.o : /usr/share/arduino/libraries/NilRTOS/nil.c
	@echo [93mNilRTOS/nil.c[0m
	@mkdir -p .build_ano/uno/NilRTOS
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/libraries/NilRTOS/nil.c
include .build_ano/uno/NilRTOS/nil.c.d

.build_ano/uno/NilRTOS/board.c.o : /usr/share/arduino/libraries/NilRTOS/board.c
	@echo [93mNilRTOS/board.c[0m
	@mkdir -p .build_ano/uno/NilRTOS
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/libraries/NilRTOS/board.c
include .build_ano/uno/NilRTOS/board.c.d

.build_ano/uno/NilRTOS/NilRTOS.c.o : /usr/share/arduino/libraries/NilRTOS/NilRTOS.c
	@echo [93mNilRTOS/NilRTOS.c[0m
	@mkdir -p .build_ano/uno/NilRTOS
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/libraries/NilRTOS/NilRTOS.c
include .build_ano/uno/NilRTOS/NilRTOS.c.d

.build_ano/uno/NilRTOS/nilcore.c.o : /usr/share/arduino/libraries/NilRTOS/nilcore.c
	@echo [93mNilRTOS/nilcore.c[0m
	@mkdir -p .build_ano/uno/NilRTOS
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/libraries/NilRTOS/nilcore.c
include .build_ano/uno/NilRTOS/nilcore.c.d






.build_ano/uno/NilRTOS/NilTwiWaitSignal.cpp.o : /usr/share/arduino/libraries/NilRTOS/NilTwiWaitSignal.cpp
	@echo [93mNilRTOS/NilTwiWaitSignal.cpp[0m
	@mkdir -p .build_ano/uno/NilRTOS
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/libraries/NilRTOS/NilTwiWaitSignal.cpp
include .build_ano/uno/NilRTOS/NilTwiWaitSignal.cpp.d

.build_ano/uno/NilRTOS/nilUtility.cpp.o : /usr/share/arduino/libraries/NilRTOS/nilUtility.cpp
	@echo [93mNilRTOS/nilUtility.cpp[0m
	@mkdir -p .build_ano/uno/NilRTOS
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/libraries/NilRTOS/nilUtility.cpp
include .build_ano/uno/NilRTOS/nilUtility.cpp.d

.build_ano/uno/NilRTOS/NilSerial.cpp.o : /usr/share/arduino/libraries/NilRTOS/NilSerial.cpp
	@echo [93mNilRTOS/NilSerial.cpp[0m
	@mkdir -p .build_ano/uno/NilRTOS
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/libraries/NilRTOS/NilSerial.cpp
include .build_ano/uno/NilRTOS/NilSerial.cpp.d








.build_ano/uno/NilRTOS/libNilRTOS.a : .build_ano/uno/NilRTOS/nil.c.o .build_ano/uno/NilRTOS/board.c.o .build_ano/uno/NilRTOS/NilRTOS.c.o .build_ano/uno/NilRTOS/nilcore.c.o .build_ano/uno/NilRTOS/NilTwiWaitSignal.cpp.o .build_ano/uno/NilRTOS/nilUtility.cpp.o .build_ano/uno/NilRTOS/NilSerial.cpp.o
	@echo [92mLinking libNilRTOS.a[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^













.build_ano/uno/DHT/DHT.cpp.o : /usr/share/arduino/libraries/DHT/DHT.cpp
	@echo [93mDHT/DHT.cpp[0m
	@mkdir -p .build_ano/uno/DHT
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/libraries/DHT/DHT.cpp
include .build_ano/uno/DHT/DHT.cpp.d








.build_ano/uno/DHT/libDHT.a : .build_ano/uno/DHT/DHT.cpp.o
	@echo [92mLinking libDHT.a[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^








.build_ano/uno/arduino/wiring.c.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c
	@echo [93marduino/wiring.c[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c
include .build_ano/uno/arduino/wiring.c.d

.build_ano/uno/arduino/wiring_digital.c.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c
	@echo [93marduino/wiring_digital.c[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c
include .build_ano/uno/arduino/wiring_digital.c.d

.build_ano/uno/arduino/wiring_shift.c.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c
	@echo [93marduino/wiring_shift.c[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c
include .build_ano/uno/arduino/wiring_shift.c.d

.build_ano/uno/arduino/hooks.c.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c
	@echo [93marduino/hooks.c[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c
include .build_ano/uno/arduino/hooks.c.d

.build_ano/uno/arduino/WInterrupts.c.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c
	@echo [93marduino/WInterrupts.c[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c
include .build_ano/uno/arduino/WInterrupts.c.d

.build_ano/uno/arduino/wiring_pulse.c.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c
	@echo [93marduino/wiring_pulse.c[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c
include .build_ano/uno/arduino/wiring_pulse.c.d

.build_ano/uno/arduino/wiring_analog.c.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c
	@echo [93marduino/wiring_analog.c[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c
include .build_ano/uno/arduino/wiring_analog.c.d






.build_ano/uno/arduino/HardwareSerial1.cpp.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp
	@echo [93marduino/HardwareSerial1.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp
include .build_ano/uno/arduino/HardwareSerial1.cpp.d

.build_ano/uno/arduino/WMath.cpp.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp
	@echo [93marduino/WMath.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp
include .build_ano/uno/arduino/WMath.cpp.d

.build_ano/uno/arduino/Tone.cpp.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp
	@echo [93marduino/Tone.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp
include .build_ano/uno/arduino/Tone.cpp.d

.build_ano/uno/arduino/PluggableUSB.cpp.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/PluggableUSB.cpp
	@echo [93marduino/PluggableUSB.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/PluggableUSB.cpp
include .build_ano/uno/arduino/PluggableUSB.cpp.d

.build_ano/uno/arduino/WString.cpp.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp
	@echo [93marduino/WString.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp
include .build_ano/uno/arduino/WString.cpp.d

.build_ano/uno/arduino/IPAddress.cpp.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp
	@echo [93marduino/IPAddress.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp
include .build_ano/uno/arduino/IPAddress.cpp.d

.build_ano/uno/arduino/Print.cpp.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp
	@echo [93marduino/Print.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp
include .build_ano/uno/arduino/Print.cpp.d

.build_ano/uno/arduino/new.cpp.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp
	@echo [93marduino/new.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp
include .build_ano/uno/arduino/new.cpp.d

.build_ano/uno/arduino/main.cpp.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp
	@echo [93marduino/main.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp
include .build_ano/uno/arduino/main.cpp.d

.build_ano/uno/arduino/HardwareSerial0.cpp.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp
	@echo [93marduino/HardwareSerial0.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp
include .build_ano/uno/arduino/HardwareSerial0.cpp.d

.build_ano/uno/arduino/Stream.cpp.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp
	@echo [93marduino/Stream.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp
include .build_ano/uno/arduino/Stream.cpp.d

.build_ano/uno/arduino/abi.cpp.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp
	@echo [93marduino/abi.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp
include .build_ano/uno/arduino/abi.cpp.d

.build_ano/uno/arduino/USBCore.cpp.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp
	@echo [93marduino/USBCore.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp
include .build_ano/uno/arduino/USBCore.cpp.d

.build_ano/uno/arduino/CDC.cpp.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp
	@echo [93marduino/CDC.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp
include .build_ano/uno/arduino/CDC.cpp.d

.build_ano/uno/arduino/HardwareSerial2.cpp.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp
	@echo [93marduino/HardwareSerial2.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp
include .build_ano/uno/arduino/HardwareSerial2.cpp.d

.build_ano/uno/arduino/HardwareSerial.cpp.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp
	@echo [93marduino/HardwareSerial.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp
include .build_ano/uno/arduino/HardwareSerial.cpp.d

.build_ano/uno/arduino/HardwareSerial3.cpp.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp
	@echo [93marduino/HardwareSerial3.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp
include .build_ano/uno/arduino/HardwareSerial3.cpp.d






.build_ano/uno/arduino/wiring_pulse.S.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.S
	@echo [93marduino/wiring_pulse.S[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -x assembler-with-cpp  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.S
include .build_ano/uno/arduino/wiring_pulse.S.d



.build_ano/uno/arduino/libarduino.a : .build_ano/uno/arduino/wiring.c.o .build_ano/uno/arduino/wiring_digital.c.o .build_ano/uno/arduino/wiring_shift.c.o .build_ano/uno/arduino/hooks.c.o .build_ano/uno/arduino/WInterrupts.c.o .build_ano/uno/arduino/wiring_pulse.c.o .build_ano/uno/arduino/wiring_analog.c.o .build_ano/uno/arduino/HardwareSerial1.cpp.o .build_ano/uno/arduino/WMath.cpp.o .build_ano/uno/arduino/Tone.cpp.o .build_ano/uno/arduino/PluggableUSB.cpp.o .build_ano/uno/arduino/WString.cpp.o .build_ano/uno/arduino/IPAddress.cpp.o .build_ano/uno/arduino/Print.cpp.o .build_ano/uno/arduino/new.cpp.o .build_ano/uno/arduino/main.cpp.o .build_ano/uno/arduino/HardwareSerial0.cpp.o .build_ano/uno/arduino/Stream.cpp.o .build_ano/uno/arduino/abi.cpp.o .build_ano/uno/arduino/USBCore.cpp.o .build_ano/uno/arduino/CDC.cpp.o .build_ano/uno/arduino/HardwareSerial2.cpp.o .build_ano/uno/arduino/HardwareSerial.cpp.o .build_ano/uno/arduino/HardwareSerial3.cpp.o .build_ano/uno/arduino/wiring_pulse.S.o
	@echo [92mLinking libarduino.a[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^















.build_ano/uno/src/main.ino.cpp.o : .build_ano/uno/src/main.ino.cpp
	@echo [93msrc/main.ino.cpp[0m
	@mkdir -p .build_ano/uno/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=168 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/libraries/NilRTOS -I/usr/share/arduino/libraries/DHT -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions -iquote src  -o $@ -c .build_ano/uno/src/main.ino.cpp
include .build_ano/uno/src/main.ino.cpp.d















.build_ano/uno/firmware.elf : .build_ano/uno/src/main.ino.cpp.o .build_ano/uno/NilRTOS/libNilRTOS.a .build_ano/uno/DHT/libDHT.a .build_ano/uno/arduino/libarduino.a
	@echo [92mLinking firmware.elf[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -Wl,-Os -Wl,--gc-sections -o $@ $^ -lm


.build_ano/uno/firmware.hex : .build_ano/uno/firmware.elf
	@echo [92mConverting to firmware.hex[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build_ano/uno/src/dependencies.d .build_ano/uno/arduino/dependencies.d .build_ano/uno/NilRTOS/dependencies.d .build_ano/uno/DHT/dependencies.d

all : .build_ano/uno/firmware.hex
	@true

